CREATE TABLE  ARBOL_INDICADOR 
   (	IDARBOL INTEGER, 
	IDOBJETIVO INTEGER, 
	IDINDICADOR INTEGER, 
	INDICADOR_PADRE INTEGER, 
	PONDERACION DECIMAL(10,3)	 
   )

CREATE TABLE  ARBOL_INDICADOR_VALORES 
   (	ID INTEGER, 
	VALOR_META DECIMAL(10,3), 
	VALOR_EJECUTADO DECIMAL(10,3), 
	FECHA_META DATETIME DEFAULT GETDATE()(), 
	FECHA_EJECUTADO DATETIME, 
	IDINDICADOR INTEGER, 
	IDDESPLIEGUE INTEGER, 
	IDARBOL INTEGER, 
	PERIODO INTEGER, 
	ANIO INTEGER	 
   )

CREATE TABLE  CAMPOS_ADICIONALES 
   (	IDCAMPO INTEGER, 
	NOMBRE NVARCHAR(128)
   )

CREATE TABLE  CARGO 

	NOMBRE NVARCHAR(128), 
	DESCRIPCION NVARCHAR(256), 
	IDPADRE INTEGER DEFAULT 0, 
	ESTADO INTEGER DEFAULT 1, 
	RESPONSABLE NVARCHAR(128), 
	EMAIL VARCHAR2(128)
   )

CREATE TABLE  CONTROL_CAMBIOS 
   (	ID INTEGER, 
	IDUSUARIO INTEGER, 
	ACCION NVARCHAR(512), 
	FECHA DATETIME DEFAULT GETDATE(), 
	VALOR_ANTERIOR NVARCHAR(16), 
	VALOR_NUEVO NVARCHAR(16), 
	ARCHIVO NVARCHAR(512), 
	COMENTARIO NVARCHAR(512), 
	IDINDICADOR INTEGER
   )

CREATE TABLE  DEPARTAMENTO 
   (	IDDEPARTAMENTO INTEGER NOT NULL, 
	NOMBRE NVARCHAR(128), 
	DESCRIPCION NVARCHAR(512), 
	IDPADRE INTEGER, 
	ESTADO INTEGER DEFAULT 1 NOT NULL
   )

CREATE TABLE  DEPARTAMENTO_OBJETIVO 
   (	ID INTEGER NOT NULL , 
	IDDEPARTAMENTO INTEGER NOT NULL , 
	IDOBJETIVO INTEGER NOT NULL 
   )

CREATE TABLE  DESPLIEGUE 
   (	IDDESPLIEGUE INTEGER, 
	IDPADRE INTEGER, 
	NOMBRE NVARCHAR(128) NOT NULL , 
	CODIGO NVARCHAR(16), 
	DESCRIPCION VARCHAR(512)
   )

CREATE TABLE  FORMULA 
   (	IDFORMULA INTEGER, 
	NOMBRE NVARCHAR(128) NOT NULL 
   )

CREATE TABLE  FRECUENCIA 
   (	IDFRECUENCIA INTEGER, 
	NOMBRE NVARCHAR(128), 
	MESES INTEGER
   )

CREATE TABLE  INDICADORES 
   (	
    IDINDICADOR INTEGER, 
	CODIGO NVARCHAR(64), 
	NIVEL_ESTRATEGICO INTEGER, 
	NOMBRE NVARCHAR(128), 
	UNIDAD INTEGER, 
	DEFINICION NVARCHAR(512), 
	FORMULA VARCHAR(512), 
	SEGMENTO INTEGER, 
	PRODUCTO INTEGER, 
	TIPO NVARCHAR(64), 
	DESPLIEGUE INTEGER, 
	FRECUENCIA INTEGER, 
	RESPONSABLE INTEGER, 
	FACILITADOR INTEGER, 
	VIGENTE INTEGER, 
	ESTADO INTEGER, 
	COMENTARIO NVARCHAR(512), 
	VIGENTE_DESDE DATETIME DEFAULT GETDATE(), 
	VIGENTE_HASTA DATETIME, 
	MANUAL INTEGER, 
	RESPONSABLE_GERENCIA INTEGER, 
	SIGNO CHAR(1) DEFAULT '+'
   )

CREATE TABLE  INDICADOR_CAMPOS 
   (	ID INTEGER, 
	IDCAMPO INTEGER, 
	IDINDICADOR INTEGER, 
	VALOR NVARCHAR(253)
   )

CREATE TABLE  OBJETIVO 
   (	IDOBJETIVO INTEGER NOT NULL , 
	CODIGO NVARCHAR(64), 
	NOMBRE NVARCHAR(128), 
	OBJETIVO_PADRE INTEGER, 
	SIGNO CHAR(1), 
	OPERACION NVARCHAR(128)
   )

CREATE TABLE  PARAMETROS_INDICADORES 
   (	DIA_INICIO INTEGER, 
	DIAS_INGRESO INTEGER, 
	MAXIMO_INGRESO INTEGER
   )

CREATE TABLE  PRODUCTO 
   (	IDPRODUCTO INTEGER, 
	NOMBRE NVARCHAR(128), 
	DESCRIPCION NVARCHAR(512)
   )

CREATE TABLE  SEGMENTACION 
   (	NIVEL INTEGER, 
	NOMBRE NVARCHAR(128)
   )

CREATE TABLE  SEGMENTOS 
   (	IDSEGMENTO INTEGER, 
	NOMBRE NVARCHAR(128), 
	DESCRIPCION NVARCHAR(512)
   )

CREATE TABLE  UNIDADES 
   (	IDUNIDAD INTEGER, 
	NOMBRE NVARCHAR(128), 
	SIMBOLO VARCHAR(16), 
	DESCRIPCION NVARCHAR(512)
   )

CREATE TABLE  USUARIO 
   (	IDUSUARIO INTEGER, 
	NOMBRE NVARCHAR(64), 
	APELLIDO NVARCHAR(64), 
	EMAIL NVARCHAR(128), 
	PWD NVARCHAR(64), 
	PWD_INIT NVARCHAR(64), 
	ESTADO CHAR(1), 
	TIPO CHAR(1), 
	ELIMINADO INTEGER, 
	FECHA DATETIME DEFAULT GETDATE()
   )