CREATE TABLE  "PRODUCTO" 
   (	"IDPRODUCTO" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"DESCRIPCION" NVARCHAR2(512), 
	 CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("IDPRODUCTO") ENABLE
   )
/
CREATE TABLE  "SEGMENTACION" 
   (	"NIVEL" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	 CONSTRAINT "SEGMENTACION_PK" PRIMARY KEY ("NIVEL") ENABLE
   )
/
CREATE TABLE  "SEGMENTOS" 
   (	"IDSEGMENTO" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"DESCRIPCION" NVARCHAR2(512), 
	 CONSTRAINT "SEGMENTOS_PK" PRIMARY KEY ("IDSEGMENTO") ENABLE
   )
/
CREATE TABLE  "UNIDADES" 
   (	"IDUNIDAD" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"SIMBOLO" VARCHAR2(16), 
	"DESCRIPCION" NVARCHAR2(512), 
	 CONSTRAINT "UNIDADES_PK" PRIMARY KEY ("IDUNIDAD") ENABLE
   )
/
CREATE TABLE  "USUARIO" 
   (	"IDUSUARIO" NUMBER, 
	"NOMBRE" NVARCHAR2(64), 
	"APELLIDO" NVARCHAR2(64), 
	"EMAIL" NVARCHAR2(128), 
	"PWD" NVARCHAR2(64), 
	"PWD_INIT" NVARCHAR2(64), 
	"ESTADO" CHAR(1), 
	"TIPO" CHAR(1), 
	"ELIMINADO" NUMBER, 
	"FECHA" DATE DEFAULT sysdate, 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO") ENABLE
   )
/
CREATE TABLE  "INDICADORES" 
   (	"IDINDICADOR" NUMBER, 
	"CODIGO" NVARCHAR2(64), 
	"NIVEL_ESTRATEGICO" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"UNIDAD" NUMBER, 
	"DEFINICION" NVARCHAR2(512), 
	"FORMULA" VARCHAR2(512), 
	"SEGMENTO" NUMBER, 
	"PRODUCTO" NUMBER, 
	"TIPO" NVARCHAR2(64), 
	"DESPLIEGUE" NUMBER, 
	"FRECUENCIA" NUMBER, 
	"RESPONSABLE" NUMBER, 
	"FACILITADOR" NUMBER, 
	"VIGENTE" NUMBER, 
	"ESTADO" NUMBER, 
	"COMENTARIO" NVARCHAR2(512), 
	"VIGENTE_DESDE" DATE DEFAULT sysdate, 
	"VIGENTE_HASTA" DATE, 
	"MANUAL" NUMBER, 
	"RESPONSABLE_GERENCIA" NUMBER, 
	"SIGNO" CHAR(1) DEFAULT '+', 
	 CONSTRAINT "INDICADORES_PK" PRIMARY KEY ("IDINDICADOR") ENABLE, 
	 CONSTRAINT "INDICADORES_FK" FOREIGN KEY ("UNIDAD")
	  REFERENCES  "UNIDADES" ("IDUNIDAD") ENABLE, 
	 CONSTRAINT "INDICADORES_FK2" FOREIGN KEY ("SEGMENTO")
	  REFERENCES  "SEGMENTOS" ("IDSEGMENTO") ENABLE, 
	 CONSTRAINT "INDICADORES_FK3" FOREIGN KEY ("PRODUCTO")
	  REFERENCES  "PRODUCTO" ("IDPRODUCTO") ENABLE, 
	 CONSTRAINT "INDICADORES_FK5" FOREIGN KEY ("FRECUENCIA")
	  REFERENCES  "FRECUENCIA" ("IDFRECUENCIA") ENABLE, 
	 CONSTRAINT "INDICADORES_FK6" FOREIGN KEY ("RESPONSABLE")
	  REFERENCES  "CARGO" ("IDCARGO") ENABLE, 
	 CONSTRAINT "INDICADORES_FK7" FOREIGN KEY ("FACILITADOR")
	  REFERENCES  "USUARIO" ("IDUSUARIO") ENABLE, 
	 CONSTRAINT "INDICADORES_FK1" FOREIGN KEY ("SEGMENTO")
	  REFERENCES  "SEGMENTACION" ("NIVEL") ENABLE
   )
/
CREATE TABLE  "OBJETIVO" 
   (	"IDOBJETIVO" NUMBER NOT NULL ENABLE, 
	"CODIGO" NVARCHAR2(64), 
	"NOMBRE" NVARCHAR2(128), 
	"OBJETIVO_PADRE" NUMBER, 
	"SIGNO" CHAR(1), 
	"OPERACION" NVARCHAR2(128), 
	 CONSTRAINT "OBJETIVO_PK" PRIMARY KEY ("IDOBJETIVO") ENABLE, 
	 CONSTRAINT "OBJETIVO_CON_FK" FOREIGN KEY ("OBJETIVO_PADRE")
	  REFERENCES  "OBJETIVO" ("IDOBJETIVO") ENABLE
   )
/
CREATE TABLE  "ARBOL_INDICADOR" 
   (	"IDARBOL" NUMBER, 
	"IDOBJETIVO" NUMBER, 
	"IDINDICADOR" NUMBER, 
	"INDICADOR_PADRE" NUMBER, 
	"PONDERACION" BINARY_DOUBLE, 
	 CONSTRAINT "ARBOL_INDICADOR_PK" PRIMARY KEY ("IDARBOL") ENABLE, 
	 CONSTRAINT "ARBOL_INDICADOR_FK" FOREIGN KEY ("IDOBJETIVO")
	  REFERENCES  "OBJETIVO" ("IDOBJETIVO") ENABLE, 
	 CONSTRAINT "ARBOL_INDICADOR_FK2" FOREIGN KEY ("IDINDICADOR")
	  REFERENCES  "INDICADORES" ("IDINDICADOR") ENABLE
   )
/
CREATE TABLE  "DESPLIEGUE" 
   (	"IDDESPLIEGUE" NUMBER, 
	"IDPADRE" NUMBER, 
	"NOMBRE" NVARCHAR2(128) NOT NULL ENABLE, 
	"CODIGO" NVARCHAR2(16), 
	"DESCRIPCION" VARCHAR2(512), 
	 CONSTRAINT "DESPLIEGUE_PK" PRIMARY KEY ("IDDESPLIEGUE") ENABLE, 
	 CONSTRAINT "DESPLIEGUE_CON" FOREIGN KEY ("IDPADRE")
	  REFERENCES  "DESPLIEGUE" ("IDDESPLIEGUE") ENABLE
   )
/
CREATE TABLE  "ARBOL_INDICADOR_VALORES" 
   (	"ID" NUMBER, 
	"VALOR_META" BINARY_FLOAT, 
	"VALOR_EJECUTADO" BINARY_FLOAT, 
	"FECHA_META" DATE DEFAULT sysdate, 
	"FECHA_EJECUTADO" DATE, 
	"IDINDICADOR" NUMBER, 
	"IDDESPLIEGUE" NUMBER, 
	"IDARBOL" NUMBER, 
	"PERIODO" NUMBER, 
	"ANIO" NUMBER, 
	 CONSTRAINT "ARBOL_INDICADOR_VALORES_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "ARBOL_INDICADOR_VALORES_CON" FOREIGN KEY ("IDINDICADOR")
	  REFERENCES  "INDICADORES" ("IDINDICADOR") ENABLE, 
	 CONSTRAINT "ARBOL_INDICADOR_VALORES_CON2" FOREIGN KEY ("IDDESPLIEGUE")
	  REFERENCES  "DESPLIEGUE" ("IDDESPLIEGUE") ENABLE, 
	 CONSTRAINT "ARBOL_INDICADOR_VALORES_CON3" FOREIGN KEY ("IDARBOL")
	  REFERENCES  "ARBOL_INDICADOR" ("IDARBOL") ENABLE
   )
/
CREATE TABLE  "CAMPOS_ADICIONALES" 
   (	"IDCAMPO" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	 CONSTRAINT "CAMPOS_ADICIONALES_PK" PRIMARY KEY ("IDCAMPO") ENABLE
   )
/
CREATE TABLE  "CARGO" 
   (	"IDCARGO" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"DESCRIPCION" NVARCHAR2(256), 
	"IDPADRE" NUMBER DEFAULT 0, 
	"ESTADO" NUMBER DEFAULT 1, 
	"RESPONSABLE" NVARCHAR2(128), 
	"EMAIL" VARCHAR2(128), 
	 CONSTRAINT "CARGO_PK" PRIMARY KEY ("IDCARGO") ENABLE, 
	 CONSTRAINT "CARGO_CON" FOREIGN KEY ("IDPADRE")
	  REFERENCES  "CARGO" ("IDCARGO") ENABLE
   )
/
CREATE TABLE  "CONTROL_CAMBIOS" 
   (	"ID" NUMBER, 
	"IDUSUARIO" NUMBER, 
	"ACCION" NVARCHAR2(512), 
	"FECHA" DATE DEFAULT sysdate, 
	"VALOR_ANTERIOR" NVARCHAR2(16), 
	"VALOR_NUEVO" NVARCHAR2(16), 
	"ARCHIVO" NVARCHAR2(512), 
	"COMENTARIO" NVARCHAR2(512), 
	"IDINDICADOR" NUMBER, 
	 CONSTRAINT "LOG_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "LOG_FK" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES  "USUARIO" ("IDUSUARIO") ENABLE, 
	 CONSTRAINT "CONTROL_CAMBIOS_CON" FOREIGN KEY ("IDINDICADOR")
	  REFERENCES  "INDICADORES" ("IDINDICADOR") ENABLE
   )
/
CREATE TABLE  "DEPARTAMENTO" 
   (	"IDDEPARTAMENTO" NUMBER NOT NULL ENABLE, 
	"NOMBRE" NVARCHAR2(128), 
	"DESCRIPCION" NVARCHAR2(512), 
	"IDPADRE" NUMBER, 
	"ESTADO" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("IDDEPARTAMENTO") ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_CON_FK" FOREIGN KEY ("IDPADRE")
	  REFERENCES  "DEPARTAMENTO" ("IDDEPARTAMENTO") ENABLE
   )
/
CREATE TABLE  "DEPARTAMENTO_OBJETIVO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IDDEPARTAMENTO" NUMBER NOT NULL ENABLE, 
	"IDOBJETIVO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_OBJETIVO_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_OBJETIVO_FK" FOREIGN KEY ("IDDEPARTAMENTO")
	  REFERENCES  "DEPARTAMENTO" ("IDDEPARTAMENTO") ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_OBJETIVO_FK2" FOREIGN KEY ("IDOBJETIVO")
	  REFERENCES  "OBJETIVO" ("IDOBJETIVO") ENABLE
   )
/
CREATE TABLE  "EXTENSIONES_META" 
   (	"ID" NUMBER, 
	"IDINDICADOR" NUMBER, 
	"FECHA" DATE, 
	"FECHAINGRESO" DATE, 
	 CONSTRAINT "EXTENSIONES_META_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "EXTENSIONES_META_FK" FOREIGN KEY ("IDINDICADOR")
	  REFERENCES  "INDICADORES" ("IDINDICADOR") ENABLE
   )
/
CREATE TABLE  "FORMULA" 
   (	"IDFORMULA" NUMBER, 
	"NOMBRE" NVARCHAR2(128) NOT NULL ENABLE, 
	 CONSTRAINT "FORMULA_PK" PRIMARY KEY ("IDFORMULA") ENABLE
   )
/
CREATE TABLE  "FRECUENCIA" 
   (	"IDFRECUENCIA" NUMBER, 
	"NOMBRE" NVARCHAR2(128), 
	"MESES" NUMBER, 
	 CONSTRAINT "FRECUENCIA_PK" PRIMARY KEY ("IDFRECUENCIA") ENABLE
   )
/
CREATE TABLE  "INDICADOR_CAMPOS" 
   (	"ID" NUMBER, 
	"IDCAMPO" NUMBER, 
	"IDINDICADOR" NUMBER, 
	"VALOR" NVARCHAR2(253), 
	 CONSTRAINT "INDICADOR_CAMPOS_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "INDICADOR_CAMPOS_FK" FOREIGN KEY ("IDCAMPO")
	  REFERENCES  "CAMPOS_ADICIONALES" ("IDCAMPO") ENABLE, 
	 CONSTRAINT "INDICADOR_CAMPOS_FK2" FOREIGN KEY ("IDINDICADOR")
	  REFERENCES  "INDICADORES" ("IDINDICADOR") ENABLE
   )
/
CREATE TABLE  "PARAMETROS_INDICADORES" 
   (	"DIA_INICIO" NUMBER, 
	"DIAS_INGRESO" NUMBER, 
	"MAXIMO_INGRESO" NUMBER
   )
/

Rem No se ha encontrado function para generar DDL.

CREATE UNIQUE INDEX  "ARBOL_INDICADOR_PK" ON  "ARBOL_INDICADOR" ("IDARBOL")
/
CREATE UNIQUE INDEX  "ARBOL_INDICADOR_VALORES_PK" ON  "ARBOL_INDICADOR_VALORES" ("ID")
/
CREATE UNIQUE INDEX  "CAMPOS_ADICIONALES_PK" ON  "CAMPOS_ADICIONALES" ("IDCAMPO")
/
CREATE UNIQUE INDEX  "CARGO_PK" ON  "CARGO" ("IDCARGO")
/
CREATE UNIQUE INDEX  "DEPARTAMENTO_OBJETIVO_PK" ON  "DEPARTAMENTO_OBJETIVO" ("ID")
/
CREATE UNIQUE INDEX  "DEPARTAMENTO_PK" ON  "DEPARTAMENTO" ("IDDEPARTAMENTO")
/
CREATE UNIQUE INDEX  "DESPLIEGUE_PK" ON  "DESPLIEGUE" ("IDDESPLIEGUE")
/
CREATE UNIQUE INDEX  "EXTENSIONES_META_PK" ON  "EXTENSIONES_META" ("ID")
/
CREATE UNIQUE INDEX  "FORMULA_PK" ON  "FORMULA" ("IDFORMULA")
/
CREATE UNIQUE INDEX  "FRECUENCIA_PK" ON  "FRECUENCIA" ("IDFRECUENCIA")
/
CREATE UNIQUE INDEX  "INDICADORES_PK" ON  "INDICADORES" ("IDINDICADOR")
/
CREATE UNIQUE INDEX  "INDICADOR_CAMPOS_PK" ON  "INDICADOR_CAMPOS" ("ID")
/
CREATE UNIQUE INDEX  "LOG_PK" ON  "CONTROL_CAMBIOS" ("ID")
/
CREATE UNIQUE INDEX  "OBJETIVO_PK" ON  "OBJETIVO" ("IDOBJETIVO")
/
CREATE UNIQUE INDEX  "PRODUCTO_PK" ON  "PRODUCTO" ("IDPRODUCTO")
/
CREATE UNIQUE INDEX  "SEGMENTACION_PK" ON  "SEGMENTACION" ("NIVEL")
/
CREATE UNIQUE INDEX  "SEGMENTOS_PK" ON  "SEGMENTOS" ("IDSEGMENTO")
/
CREATE UNIQUE INDEX  "UNIDADES_PK" ON  "UNIDADES" ("IDUNIDAD")
/
CREATE UNIQUE INDEX  "USUARIO_PK" ON  "USUARIO" ("IDUSUARIO")
/

Rem No se ha encontrado package para generar DDL.

Rem No se ha encontrado procedure para generar DDL.

 CREATE SEQUENCE   "ARBOL_INDICADOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ARBOL_INDICADOR_VALORES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ARBOL_INDICADOR_VALORES_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ARBOL_INDICADOR_VALORES_SEQ3"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1441 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "AREA2_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "AREA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CAMPOS_ADICIONALES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CARGO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DEPARTAMENTO_OBJETIVO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DEPARTAMENTO_OBJETIVO_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DEPARTAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DESPLIEGUE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EXTENSIONES_META_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "FORMULA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "FRECUENCIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "IDUSUARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "INDICADORES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "INDICADOR_CAMPOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "OBJETIVO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "SEGMENTOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "UNIDADES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "USUARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

Rem No se ha encontrado synonym para generar DDL.

CREATE OR REPLACE TRIGGER  "BI_ARBOL_INDICADOR" 
  before insert on "ARBOL_INDICADOR"               
  for each row  
begin   
    select "ARBOL_INDICADOR_SEQ".nextval into :NEW.IDARBOL from dual; 
end; 

/
ALTER TRIGGER  "BI_ARBOL_INDICADOR" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ARBOL_INDICADOR_VALORES" 
  before insert on "ARBOL_INDICADOR_VALORES"               
  for each row  
begin   
    select "ARBOL_INDICADOR_VALORES_SEQ3".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ARBOL_INDICADOR_VALORES" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_CAMPOS_ADICIONALES" 
  before insert on "CAMPOS_ADICIONALES"               
  for each row  
begin   
    select "CAMPOS_ADICIONALES_SEQ".nextval into :NEW.IDCAMPO from dual; 
end; 

/
ALTER TRIGGER  "BI_CAMPOS_ADICIONALES" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_CARGO" 
  before insert on "CARGO"               
  for each row  
begin   
    select "CARGO_SEQ".nextval into :NEW.IDCARGO from dual; 
end; 

/
ALTER TRIGGER  "BI_CARGO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DEPARTAMENTO" 
  before insert on "DEPARTAMENTO"               
  for each row  
begin   
    select "DEPARTAMENTO_SEQ".nextval into :NEW.IDDEPARTAMENTO from dual; 
end; 

/
ALTER TRIGGER  "BI_DEPARTAMENTO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DEPARTAMENTO_OBJETIVO" 
  before insert on "DEPARTAMENTO_OBJETIVO"               
  for each row  
begin   
    select "DEPARTAMENTO_OBJETIVO_SEQ2".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_DEPARTAMENTO_OBJETIVO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DESPLIEGUE" 
  before insert on "DESPLIEGUE"               
  for each row  
begin   
    select "DESPLIEGUE_SEQ".nextval into :NEW.IDDESPLIEGUE from dual; 
end; 

/
ALTER TRIGGER  "BI_DESPLIEGUE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EXTENSIONES_META" 
  before insert on "EXTENSIONES_META"               
  for each row  
begin   
    select "EXTENSIONES_META_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_EXTENSIONES_META" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_FORMULA" 
  before insert on "FORMULA"               
  for each row  
begin   
    select "FORMULA_SEQ".nextval into :NEW.IDFORMULA from dual; 
end; 

/
ALTER TRIGGER  "BI_FORMULA" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_FRECUENCIA" 
  before insert on "FRECUENCIA"               
  for each row  
begin   
    select "FRECUENCIA_SEQ".nextval into :NEW.IDFRECUENCIA from dual; 
end; 

/
ALTER TRIGGER  "BI_FRECUENCIA" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_INDICADORES" 
  before insert on "INDICADORES"               
  for each row  
begin   
    select "INDICADORES_SEQ".nextval into :NEW.IDINDICADOR from dual; 
end; 

/
ALTER TRIGGER  "BI_INDICADORES" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_INDICADOR_CAMPOS" 
  before insert on "INDICADOR_CAMPOS"               
  for each row  
begin   
    select "INDICADOR_CAMPOS_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_INDICADOR_CAMPOS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_LOG" 
  before insert on "CONTROL_CAMBIOS"               
  for each row  
begin   
    select "LOG_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_LOG" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_OBJETIVO" 
  before insert on "OBJETIVO"               
  for each row  
begin   
    select "OBJETIVO_SEQ".nextval into :NEW.IDOBJETIVO from dual; 
end; 

/
ALTER TRIGGER  "BI_OBJETIVO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_PRODUCTO" 
  before insert on "PRODUCTO"               
  for each row  
begin   
    select "PRODUCTO_SEQ".nextval into :NEW.IDPRODUCTO from dual; 
end; 

/
ALTER TRIGGER  "BI_PRODUCTO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_SEGMENTOS" 
  before insert on "SEGMENTOS"               
  for each row  
begin   
    select "SEGMENTOS_SEQ".nextval into :NEW.IDSEGMENTO from dual; 
end; 

/
ALTER TRIGGER  "BI_SEGMENTOS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_UNIDADES" 
  before insert on "UNIDADES"               
  for each row  
begin   
    select "UNIDADES_SEQ".nextval into :NEW.IDUNIDAD from dual; 
end; 

/
ALTER TRIGGER  "BI_UNIDADES" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_USUARIO" 
  before insert on "USUARIO"               
  for each row  
begin   
    select "IDUSUARIO_SEQ".nextval into :NEW.IDUSUARIO from dual; 
end; 

/
ALTER TRIGGER  "BI_USUARIO" ENABLE
/


